// THIS FILE IS AUTO-GENERATED BY scripts/generatePostMap.mjs
import type { FC } from 'react';

export const postMap: Record<string, () => Promise<{ default: FC }>> = {
  'examples': () => import('./examples'),
};