import {readdir, writeFile} from 'fs/promises';
import path from 'path';

const notesDir = path.resolve('app/notebook/notes');
const outputFile = path.resolve(notesDir, 'postMap.ts');

function toSlug(filename) {
  return filename.replace(/\.tsx$/, '');
}

async function generate() {
  const files = (await readdir(notesDir)).filter(f => f.endsWith('.tsx') && f !== 'postMap.ts');

  const imports = files
    .map(f => {
      const slug = toSlug(f);
      return `  '${slug}': () => import('./${slug}'),`;
    })
    .join('\n');

  const content = `
// THIS FILE IS AUTO-GENERATED BY scripts/generatePostMap.mjs
import type { FC } from 'react';

export const postMap: Record<string, () => Promise<{ default: FC }>> = {
${imports}
};
`.trim();

  await writeFile(outputFile, content);
  console.log(`Generated postMap.ts with ${files.length} entries.`);
}

generate();
